### ISSUE TITLE
Training.py modification

### ISSUE THREAD

**Issue by visriv** [slim1017/VaDE#19]
I am new to writing codes; it has been instructed to "Replace keras/engine/training.py by training.py in this repository!!", but I can not understand where in this repository I make the changes?

Please someone help me.

**Comment by baohq1595** [comment]
@visriv **keras/engine/training.py** is where keras library is installed on your system. For ex: using anaconda, just copy the **training.py** from repo to **Anaconda3\envs\my_env\Lib\site-packages\keras\engine\training.py**

**Comment by visriv** [comment]
Thank you. This makes it clear
