### ISSUE TITLE
ValueError: Invalid argument "add_optimizer" passed to K.function with Theano backend

### ISSUE THREAD

**Issue by michelleowen** [slim1017/VaDE#7]
Hi, I cloned your git and try to run "python VaDE.py mnist". But got the following errors:

> Using Theano backend.
training on: mnist
pretrain weights loaded!
Traceback (most recent call last):
  File "VaDE.py", line 266, in <module>
    callbacks=[epoch_begin])
  File "build/bdist.macosx-10.7-x86_64/egg/keras/engine/training.py", line 1607, in fit
    '''Generates predictions for the input samples from a data generator.
  File "build/bdist.macosx-10.7-x86_64/egg/keras/engine/training.py", line 996, in _make_train_function
    check_array_lengths(x, y, sample_weights)
  File "build/bdist.macosx-10.7-x86_64/egg/keras/backend/theano_backend.py", line 1231, in function
ValueError: Invalid argument "add_optimizer" passed to K.function with Theano backend

Please advise.

**Comment by michelleowen** [comment]
which theano version did you use?

**Comment by michelleowen** [comment]
changed the wrong training.py file. Never mind.

**Comment by JasonKwok17** [comment]
Which training.py file should I change ?Pls help me,thanks a lot!
@michelleowen 

![image](https://user-images.githubusercontent.com/34647723/37268722-4677c722-2602-11e8-9427-749221fbffe2.png)

**Comment by dhanajitb** [comment]
As mentioned in the README.md:
"Replace keras/engine/training.py by training.py in this repository!!"

**Comment by dhanajitb** [comment]
@JasonKwok17 
As mentioned in the README.md:
"Replace keras/engine/training.py by training.py in this repository!!"
